import machine
import time
plano1 = machine.Pin(15, machine.Pin.OUT)
led2 = machine.Pin(14, machine.Pin.OUT)
led1 = machine.Pin(13, machine.Pin.OUT)
led3 = machine.Pin(12, machine.Pin.OUT)
led4 = machine.Pin(2, machine.Pin.OUT)
led5 = machine.Pin(0, machine.Pin.OUT)
led6 = machine.Pin(4, machine.Pin.OUT)
led7 = machine.Pin(5, machine.Pin.OUT)

plano1.on()
led1.on()
time.sleep_ms(200)
led1.off()
led2.on()
time.sleep_ms(200)
led2.off()
led3.on()
time.sleep_ms(200)
led3.off()
led4.on()
time.sleep_ms(200)
led4.off()
led5.on()
time.sleep_ms(200)
led5.off()
led6.on()
time.sleep_ms(200)
led6.off()
led7.on()
time.sleep_ms(200)

